[package]
org = "carrental"
name = "car_rental_system"
version = "0.1.0"
distribution = "2201.8.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
artifactId = "grpc-netty-shaded"
version = "1.53.0"
groupId = "io.grpc"

[[platform.java11.dependency]]
artifactId = "grpc-protobuf"
version = "1.53.0" 
groupId = "io.grpc"

[[platform.java11.dependency]]
artifactId = "grpc-stub"
version = "1.53.0"
groupId = "io.grpc"

[[platform.java11.dependency]]
artifactId = "protobuf-java"
version = "3.21.12"
groupId = "com.google.protobuf"

[[platform.java11.dependency]]
artifactId = "protobuf-java-util"
version = "3.21.12"
groupId = "com.google.protobuf"